//___FILEHEADER___
//  This file was generated by MVVM Template generator

import Foundation
import RxSwift
import RxRelay

class ___VARIABLE_moduleName___ViewModel {

    let disposeBag = DisposeBag()
    
    let errorMessage = PublishedSubject<String>()
    
    init() {
        
    }
}
